### ISSUE TITLE
Rebase latest release tag from upstream

### ISSUE THREAD

**Issue by iternity-dotcom** [iternity-dotcom/minio#12]
Based on the latest "iternity" branch.

**Comment by tristanexsquare** [comment]
I have started to rebase on top of tag _RELEASE.2021-10-13T00-23-17Z_ two weeks ago. There are a lot of changes and it consumes a lot of time to merge these changes into the refactoring that we have done. Unittesting and Minttesting on Mac/Linux is also part of the merge/rebase process. I will create temporary branches suffixed with _-rb_ for each of the original branches:

- refactoring/fs-v1-storage(-rb)
- feature/fs-xl-storage(-rb)
- feature/fs-version-lock(-rb)
- iternity(-rb)

As soon as everything is complete we can of course rename them to override the original branches. At the moment the first two branches are nearly complete.

**Comment by tristanexsquare** [comment]
The first 3 branches have been rebased and testet with unittests and minttests on macOs and Linux. I have executed the mint tests with nas and nasxl mode.

**Comment by tristanexsquare** [comment]
iternity branch has been rebased (currently named iternity-rb). I Could skip some commits:

```
pick 8ac1ec109 nasxl: Fix uninitialized bucket CreationDate
pick 116e86d01 Fixed categorization of nested folder-objects into prefixes and objects within 'ListObjects' function of 'fs-v1.go'. This is only relevant for nasxl mode. Only xlStorage format allows nested folder-objects.
skip 8630f4289 fix: lint errors after upgrading golangci-lint (#12368)
pick 687a768b6 GitHub: Run workflows on iternity and hotfix/** branches
pick 6d03f5050 GitHub: Only run automated tests on the main 'iternity' branch
pick e75e39698 fs-v1-xl-storage: Use unique tmp paths for each MinIO instance
pick 025f3bb1c fs-v1-multipart: Try to get PartInfo from disk instead of meta file
pick 32936634e fs-v1-multipart: Do not persist Metadata
pick f8b028890 Use synchronous I/O only for meta files
pick ab2e369d6 Delete files only when needed
pick b0e228b7a delete the empty dirs after renamedata
skip 9c3466625 fix: etcd IAM encryption fails due to incorrect kms.Context (#12431)
pick 9087b7b22 Added caching for bucket metadata in nasxl mode
pick 1742105b7 moved fsCreateFile to test
pick 38b84565c Improved efficiency of checkPathLength
skip a7d680139 fix: all levels deep flat key match (#12996)
skip 9be6c24b3 CI: Activate additional linters in .golangci.yml
skip 90412790c fix: remove all unused code (#12360)
skip 14d70ec48 Golint: Remove unused functions
pick 1caac54cb Golint: Use consistent receiver name in fs-v1-xl-storage.go
```

Tested with unittests and minttests on macos and linux. I have executed the mint tests with nas and nasxl mode.

**Comment by tristanexsquare** [comment]
Renamed Old Branches:
```
refactoring/fs-v1-storage => refactoring/fs-v1-storage-old
feature/fs-xl-storage => feature/fs-xl-storage-old
feature/fs-version-lock => feature/fs-version-lock-old
```

Renamed rebased Branches:
```
refactoring/fs-v1-storage-rb => refactoring/fs-v1-storage
feature/fs-xl-storage-rb => feature/fs-xl-storage
feature/fs-version-lock-rb => feature/fs-version-lock
```

**Comment by rluetzner** [comment]
The rebase is finished and there's nothing left to do.
