### ISSUE TITLE
Identify missing S3 system tests

### ISSUE THREAD

**Issue by aweisser** [iternity-dotcom/minio#2]
**Is your feature request related to a problem? Please describe.**
With https://github.com/minio/minio/pull/11783 you can get a code coverage report from a system test run (like Mint).
As discussed in https://minio.slack.com/archives/C3NDUB8UA/p1615891367010200 the Mint test only covers 25% of the Minio code because Mint is only focused on the S3 API. And the S3 API is only a part of Minios public interface.

So to evaluate the "real" code coverage of Mint we need to identifiy which of the *-handlers.go files implements the S3 API.
We can then filter the total coverage to only those *-handlers.go files.

**Describe the solution you'd like**
We need to know which AWS S3 functions are implemented where in Minio (esp. *-handler*.go files) and also 
which offical S3 functions are not implemented by Minio at all.

**Describe alternatives you've considered**
We already asked this in minio.slack thread (see above). But did not get an answer so far.

**Additional context**
We can focus on the "AWS S3 Simple Storage Service API" (https://docs.aws.amazon.com/AmazonS3/latest/API/API_Operations_Amazon_Simple_Storage_Service.html)

**Comment by andrebruch** [comment]
The following files implement the S3 API:
`acl-handlers.go`  
`admin-bucket-handlers.go`               
`admin-handlers-config-kv.go` 
`admin-handlers-users.go` 
`admin-handlers.go` 
`bucket-handlers.go` 
`bucket-lifecycle-handlers.go`
`bucket-listobjects-handlers.go`
`bucket-notification-handlers.go`
`bucket-policy-handlers.go`
`listen-notification-handlers.go`
`object-handlers.go`
`dummy-handlers.go` (collection of dummy APIs)

**Comment by iternity-dotcom** [comment]
@andrebruch What about the following?

https://github.com/minio/minio/blob/master/cmd/bucket-versioning-handler.go

https://github.com/minio/minio/blob/master/cmd/sts-handlers.go

**Comment by aweisser** [comment]
@andrebruch Please additionally create a diff between the actions defined by the "Amazon Simple Storage Service API" (https://docs.aws.amazon.com/AmazonS3/latest/API/API_Operations_Amazon_Simple_Storage_Service.html) and the routes mappend in api-routers.go. I'd like to know if these two have an 1:1 relationship.

I already created the following Excel file with two columns (sorted alphabetically) listing the different api names used in api-router.go and the Amazon spec respectively. You can find the Excel file in our Teams Files section.

Please edit the excel table so that equivalent api names are in the same row.

**Comment by andrebruch** [comment]
> https://github.com/minio/minio/blob/master/cmd/bucket-versioning-handler.go

I was looking for files with the pattern *-handler**S**.go.
I'll check right now to see if I missed anything.

> https://github.com/minio/minio/blob/master/cmd/sts-handlers.go

I thought the STS API was considered separately from the S3 API.

**Comment by aweisser** [comment]
>> I thought the STS API was considered separately from the S3 API.
You're right. It's not part of the S3 API but there is a corresponding AWS STS API.
https://docs.aws.amazon.com/STS/latest/APIReference/welcome.html

Ok. Let's focus on S3 only, since Mint seems to be S3 specific test suite (according to Minio authorities).

**Comment by aweisser** [comment]
As an interim result I filtered our current code coverage report (see all.coverage.mint.count.xlsx in our Teams channel) to just the important handlers.
We still only have a code coverage of about 28% (for just those handlers).


Important | Filter | Statements | Covered | Coverage | Percent of total code
-- | -- | -- | -- | -- | --
handler | *acl*handler* | 115 | 0 | 0% | 0%
handler | */admin*handler* | 1768 | 27 | 2% | 3%
handler | */bucket*handler* | 1258 | 475 | 38% | 2%
handler | */object*handler* | 1982 | 895 | 45% | 3%
handler | */listen-notification-handler* | 86 | 59 | 69% | 0%
sum | SUM | 5209 | 1456 | 28% | 8%

**Comment by andrebruch** [comment]
I have updated the list again.

**Comment by andrebruch** [comment]
Important | Filter | Statements | Covered | Coverage | Percent of total code
-- | -- | -- | -- | -- | --
handler | */bucket-encryption-handlers.go | 76 | 14 | 18% | 0%
handler | */bucket-handlers.go | 756 | 285 | 38% | 1%
handler | */bucket-lifecycle-handlers.go | 76 | 0 | 0% | 0%
handler | */bucket-listobjects-handlers.go | 148 | 93 | 63% | 0%
handler | */bucket-policy-handlers.go | 76 | 34 | 45% | 0%
handler | */bucket-policy-handlers.go | 76 | 34 | 45% | 0%
handler | */bucket-versioning-handler.go | 52 | 32 | 62% | 0%
handler | */object-handlers.go | 1892 | 828 | 44% | 3%
sum | SUM | 3152 | 1320 | 42% | 5%
