### ISSUE TITLE
gateway nasxl: Objects are created with NULL versions and can be deleted in a bucket with Object-Lock with a set global retention

### ISSUE THREAD

**Issue by rluetzner** [iternity-dotcom/minio#24]
## Expected Behavior

Object-Lock depends on versioning and therefore every uploaded object should get a unique version ID.

## Current Behavior

One of our customers observed that sometimes objects are created that have a NULL version. These objects are also unaffected by the existing retention policy and can be deleted at any time.

## Steps to Reproduce (for bugs)

We don't know yet how to reproduce the issue. It seems to happen consistently on the customer system which is using S3 Browser v10.3.1 as a client.

If versioning is disabled then NULL versions are possible, but versioning cannot be disabled for buckets created with Object-Lock.

```text
$ mc retention info --default admin/locked-bucket
GOVERNANCE mode is enabled for 3DAYS.
```

**Comment by rluetzner** [comment]
I've looked into this again, but was unable to reproduce the behavior with neither S3Browser nor aws-cli.

**Comment by rluetzner** [comment]
I found a possibility where the function 'mustGetUUID()' in object-api-utils.go could return an empty string without throwing an error. That is however related to an "invalid UUID" being returned by the uuid package, which is unlikely. I have no idea what an invalid UUID might even look like. Nevertheless if we don't find anything else we might just change the code here to log an error or panic and see if this is what's creating the bug.

**Comment by rluetzner** [comment]
@aweisser fyi:

Here's an excerpt from object-api-utils.go:

```golang
// mustGetUUID - get a random UUID.
func mustGetUUID() string {
	u, err := uuid.NewRandom()
	if err != nil {
		logger.CriticalIf(GlobalContext, err)
	}

	return u.String()
}
```

and the definition of `Uuid.String()`:

```golang
// URN returns the RFC 2141 URN form of uuid,
// urn:uuid:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx,  or "" if uuid is invalid.
func (uuid UUID) URN() string {
	var buf [36 + 9]byte
	copy(buf[:], "urn:uuid:")
	encodeHex(buf[9:], uuid)
	return string(buf[:])
}
```

An _invalid_ UUID would return an empty string which is later mapped to "null" when added to xl.meta. I have no idea how the UUID might be invalid without throwing an error in the piece of code posted above, but from what I can see this looks like the only possibility where a "null" version could be created.

----

There is however a path I did not follow up on. At a certain point PutObject checks if it is operating on a versioned bucket. In case that return value is wrong we might also end up with "null" versions, although I'd have to check if that is indeed true or if a version ID is **always** generated.

**Comment by rluetzner** [comment]
I just checked again and `logger.CriticalIf(...)` says it would fail the current Go routine with a panic. If any error happened while generating the UUID, we shouldn't end up with an empty string, even though the function does not contain an early return.

However, it might be worth to verify if what the comment of `logger.CriticalIf(...)` says is actually true.

**Comment by aweisser** [comment]
_>> However, it might be worth to verify if what the comment of logger.CriticalIf(...) says is actually true._

It is.
```golang
// CriticalIf logs the provided error on the console. It fails the
// current go-routine by causing a "panic(ErrCritical)"
func CriticalIf(ctx context.Context, err error, errKind ...interface{}) {
	if err != nil {
		LogIf(ctx, err, errKind...)
		panic(ErrCritical)
	}
}
```

**Comment by aweisser** [comment]
@rluetzner 
_>> At a certain point PutObject checks if it is operating on a versioned bucket_

Maybe our distributed scenario with multiple Minio instances running against the same NAS backend causes such a problem. Maybe one of the Minio instances thinks that it's not a versioned bucket because it's running against stale data...

**Comment by rluetzner** [comment]
> Maybe one of the Minio instances thinks that it's not a versioned bucket because it's running against stale data...

I like the idea. We should check if that is possible. Although I don't think it can be caused by stale information. Object-locked buckets are created as versioned from the start and it's not like the error occurs on a newly created bucket. It's rather semi-consistently reproducible on existing object locked buckets.
The distributed setup might however cause other issues. I actually don't know exactly where the information is stored. If it is stored in etcd and one of the MinIO instances cannot connect that might also be the cause.

**Comment by aweisser** [comment]
@rluetzner: Or what if this `opts.VersionID` is already set to `"null"` (or to the constant `nullVersionID` resp.)?
Then `mustGetUUID()` would never be called ...
![grafik](https://user-images.githubusercontent.com/1389655/170317807-b3efdbea-78ab-4f14-ad30-bafa4718cee5.png)

**Comment by rluetzner** [comment]
Interesting. The client is using conventional tools (AWS-CLI and S3 Browser IIRC) so it's unlikely, but not impossible. We should be able to figure that out from the nginx logs. I'm pretty sure I would have noticed that, but it doesn't hurt to check twice.

**Comment by aweisser** [comment]
@rluetzner I don’t understand your latest comment.

**Comment by rluetzner** [comment]
Sorry for the confusion. I think that `opts.VersionID` is a request parameter and as such should be visible in the server logs. I'm not 100% sure though, but I remember looking this up at one point.

**Comment by rluetzner** [comment]
My assumption is correct, see `putOpts(...)` in `object-api-options.go`:

```golang
func putOpts(ctx context.Context, r *http.Request, bucket, object string, metadata map[string]string) (opts ObjectOptions, err error) {
	versioned := globalBucketVersioningSys.Enabled(bucket)
	vid := strings.TrimSpace(r.URL.Query().Get(xhttp.VersionID))
	[...]
	opts.VersionID = vid
	opts.Versioned = versioned
	opts.MTime = mtime
	return opts, nil
}
```

`opts.VersionID` represents a query parameter. I'll have to test if a "null" version is even valid and as I've mentioned before we should be able to verify if this happens by looking at the NGINX server logs.

----

I've also followed `globalBucketVersioningSys.Enabled(bucket)` for a while. It looks like the metadata if a bucket is versioned or not is persisted in `.minio.sys/buckets/<bucketname>/.metadata.bin`. The function reading the config looks like any errors bubble up. That is all fine and well, but

```golang
// Enabled enabled versioning?
func (sys *BucketVersioningSys) Enabled(bucket string) bool {
	vc, err := globalBucketMetadataSys.GetVersioningConfig(bucket)
	if err != nil {
		return false
	}
	return vc.Enabled()
}
```

So...in case we cannot read the config we just assume that versioning is disabled. The error is also dropped and not logged anywhere, so it's impossible to track in the current code. The behavior might be caused by a transient GlusterFS error where the bucket config is not available, but the object can still be written successfully.

This explanation seems more plausible to me than getting an invalid UUID from the system.

**Comment by rluetzner** [comment]
I followed up on the `opts.VersionID` path. It is theoretically possible to upload a file and specify `versionId=null` in the query string. However, none of the S3 clients used by our customer supports something like this (not even the low level aws-cli commands).

I was able to force this via curl:

```bash
file=test.txt
bucket=locked
resource="/${bucket}/${file}?versionId=null"
contentType="application/text"
dateValue=`date -R`
stringToSign="PUT\n\n${contentType}\n${dateValue}\n${resource}"
s3Key=icas
s3Secret=supersecret
signature=`echo -en ${stringToSign} | openssl sha1 -hmac ${s3Secret} -binary | base64`
curl -v -L -X PUT -T "${file}" \
  -H "Host: localhost" \
  -H "Date: ${dateValue}" \
  -H "Content-Type: ${contentType}" \
  -H "Authorization: AWS ${s3Key}:${signature}" \
  "http://localhost:8080${resource}"
```

My MinIO servers are load balanced by a local sidekick instance running on localhost:8080 in this case.

As suspected this is directly visible in the NGINX access logs:

```text
ts=2022-05-27T10:37:32+00:00 remote_addr=10.10.10.1 remote_user=- request="PUT /locked/test.txt?versionId=null HTTP/1.1" http_status=200 status=200 body_bytes_sent=25 http_referer="-" http_user_agent="curl/7.83.1" http_x_forwarded_for="127.0.0.1" request_length=368 server_name="" method=PUT request_method="PUT" request_time=0.052
```
